FOGL-2271B - Refactoring to support South C server + FOGL-1000 values
foglamp/foglamp-south-playback pull request #5
Opened 2019-02-06 10:58 UTC by amarendra-dianomic

2019-02-06 14:10 UTC, MarkRiddoch submitted a review, later dismissed

2019-02-06 16:34 UTC, praveen-garg requested changes

2019-02-06 16:34 UTC, praveen-garg commented on python/foglamp/plugins/south/playback/playback.py
> +    _LOGGER.info("plugin_start called")
Please remove this log

2019-02-06 16:34 UTC, praveen-garg commented on VERSION.south.playback
> +foglamp_south_playback_version=2.0.0
I think, we will need to make this 1.5.0

2019-02-06 16:34 UTC, praveen-garg commented on VERSION.south.playback
>  foglamp_version>=1.4.1
and this will be 1.5.0 on cutoff but not in develop today

2019-02-06 16:34 UTC, praveen-garg commented on python/foglamp/plugins/south/playback/playback.py
> +        'version': '2.0.0',
as above

2019-02-07 10:50 UTC, amarendra-dianomic commented
@praveen-garg feedback changes done. Pl check.

2019-02-07 12:02 UTC, Singhal-Vaibhav approved these changes

2019-02-07 12:03 UTC, praveen-garg approved these changes

2019-02-07 12:05 UTC, merged